import path from "pathe";
import { PACKAGE_NAME, PUBLIC_ASSET_PREFIX, VIRTUAL_MODULE_ID } from "./constants.js";
import type { ScannedAsset } from "./types.js";

/**
 * Generates the ambient declaration file for  virtual module.
 * This is the sole source of type information — the runtime module
 * itself carries no type annotations.
 */
export function generateTypes(assets: ScannedAsset[], directories: string[]): string {
  const assetMapEntries = assets
    .map((a) => {
      const importType = a.path.startsWith(PUBLIC_ASSET_PREFIX)
        ? "string;"
        : `Promise<typeof import("${path.normalize(a.absolute)}")>;`;

      return `    "${a.path}": ${importType}`;
    })
    .join("\n");

  const directoryUnion = directories.length
    ? directories.map((d) => `"${d}"`).join(" | ")
    : "never";

  return `// This file is auto-generated by ${PACKAGE_NAME}. Do not edit by hand.
declare module "${VIRTUAL_MODULE_ID}" {
  /**
   * Non-public entries resolve to a Promise of the full module namespace
   * (not the unwrapped default export), matching the shape Astro's
   * \`<Image src>\` accepts directly without needing to \`await\` first.
   * Generated from the contents of your configured assets directory (plus
   * \`public:\`-prefixed passthrough entries for the public directory).
   */
  interface AssetMap {
${assetMapEntries || "    // no assets found in the configured directory"}
  }

   /** Any valid key of {@link AssetMap} — i.e. every known asset path. */
  type AssetPath = keyof AssetMap;

  /** Top-level subdirectories found under the configured assets directory. */
  type AssetDirectory = ${directoryUnion};

  type AssetPathsIn<T extends AssetDirectory> = Extract<AssetPath, \`\${T}/\${string}\`>;

  interface AssetFn {
     /**
     * Lazily resolve an asset by path. The underlying module isn't bundled until this call actually runs —
     * useful for large or rarely-used assets you don't want shipped to
     * every page that imports from this module.
     *
     * @param path - A known asset path, or a \`public:\`-prefixed public
     *   directory path (returned synchronously as-is, unvalidated).
     * 
     * @throws If \`path\` isn't a known asset — the error message includes
     *   a suggested correction when a close match exists.
     */
    <P extends AssetPath>(path: P): AssetMap[P];

    /** Type guard: narrows \`path\` to {@link AssetPath} if it's a known asset. */
    exists(path: string): path is AssetPath;

    /** All known asset paths. */
    list(): readonly AssetPath[];

    /** Known asset paths under a given top-level directory. */
    list<P extends AssetDirectory>(directory: P): readonly AssetPathsIn<P>[];
  }

  export const asset: AssetFn;
}

`;
}
