import path from "pathe";
import { PACKAGE_NAME, VIRTUAL_MODULE_ID } from "./constants.js";
import type { ScannedAsset } from "./types.js";

/**
 * Generates the ambient declaration file for  virtual module.
 * This is the sole source of type information — the runtime module
 * itself carries no type annotations.
 */
export function generateTypes(assets: ScannedAsset[], directories: string[]): string {
  const assetMapEntries = assets
    .map((a) => `    "${a.path}": typeof import("${path.normalize(a.absolute)}").default;`)
    .join("\n");

  const directoryUnion = directories.length
    ? directories.map((d) => `    | "${d}"`).join("\n")
    : "    | never";

  return `// This file is auto-generated by ${PACKAGE_NAME}. Do not edit by hand.
declare module "${VIRTUAL_MODULE_ID}" {
  interface AssetMap {
${assetMapEntries || "    // no assets found in the configured directory"}
  }

  type AssetPath = keyof AssetMap;

  type AssetDirectory =
${directoryUnion};

  type AssetPathsIn<T extends AssetDirectory> = Extract<AssetPath, \`\${T}/\${string}\`>;

  interface AssetFn {
    <P extends AssetPath>(path: P): AssetMap[P];

    exists(path: string): path is AssetPath;

    list(): readonly AssetPath[];
    list<P extends AssetDirectory>(directory: P): readonly AssetPathsIn<P>[];
  }

  export const asset: AssetFn;
}
   
`;
}
